/**
 * @fileoverview This file contains an enum of all the possible opcodes within the scratch-vm.
 */


// TODO: Add extension blocks.
// TODO: Add hidden and internal blocks.

/**
 * This enum contains all the valid opcodes used in a Scratch project.
 * However, this currently does not contain any extension opcodes.
 */
export enum Opcode {
	// Motion Opcodes
	MOTION_MOVESTEPS,
	MOTION_TURNRIGHT,
	MOTION_TURNLEFT,
	MOTION_GOTO,
	MOTION_GOTOXY,
	MOTION_GLIDETO,
	MOTION_GLIDESECSTOXY,
	MOTION_POINTINDIRECTION,
	MOTION_POINTTOWARDS,
	MOTION_CHANGEXBY,
	MOTION_SETX,
	MOTION_CHANGEYBY,
	MOTION_SETY,
	MOTION_IFONEDGEBOUNCE,
	MOTION_SETROTATIONSTYLE,
	MOTION_XPOSITION,
	MOTION_YPOSITION,
	MOTION_DIRECTION,

	// Looks Opcodes
	LOOKS_SAYFORSECS,
	LOOKS_SAY,
	LOOKS_THINKFORSECS,
	LOOKS_THINK,
	LOOKS_SWITCHCOSTUMETO,
	LOOKS_NEXTCOSTUME,
	LOOKS_SWITCHBACKDROPTO,
	LOOKS_SWITCHBACKDROPTOANDWAIT,
	LOOKS_NEXTBACKDROP,
	LOOKS_CHANGESIZEBY,
	LOOKS_SETSIZETO,
	LOOKS_CHANGEEFFECTBY,
	LOOKS_SETEFFECTTO,
	LOOKS_CLEARGRAPHICEFFECTS,
	LOOKS_SHOW,
	LOOKS_HIDE,
	LOOKS_GOTOFRONTBACK,
	LOOKS_GOFORWARDBACKWARDLAYERS,
	LOOKS_COSTUMENUMBERNAME,
	LOOKS_BACKDROPNUMBERNAME,
	LOOKS_SIZE,

	// Sound Opcodes
	SOUND_PLAYUNTILDONE,
	SOUND_PLAY,
	SOUND_STOPALLSOUNDS,
	SOUND_CHANGEEFFECTBY,
	SOUND_SETEFFECTTO,
	SOUND_CLEAREFFECTS,
	SOUND_CHANGEVOLUMEBY,
	SOUND_SETVOLUMETO,
	SOUND_VOLUME,

	// Event Opcodes
	EVENT_WHENFLAGCLICKED,
	EVENT_WHENKEYPRESSED,
	EVENT_WHENTHISSPRITECLICKED,
	EVENT_WHENSTAGECLICKED,
	EVENT_WHENBACKDROPSWITCHESTO,
	EVENT_WHENGREATERTHAN,
	EVENT_WHENBROADCASTRECEIVED,
	EVENT_BROADCAST,
	EVENT_BROADCASTANDWAIT,

	// Control Opcodes
	CONTROL_WAIT,
	CONTROL_REPEAT,
	CONTROL_FOREVER,
	CONTROL_IF,
	CONTROL_IF_ELSE,
	CONTROL_WAIT_UNTIL,
	CONTROL_REPEAT_UNTIL,
	CONTROL_STOP,
	CONTROL_START_AS_CLONE,
	CONTROL_CREATE_CLONE_OF,
	CONTROL_DELETE_THIS_CLONE,

	// Sensing Opcodes
	SENSING_TOUCHINGOBJECT,
	SENSING_TOUCHINGCOLOR,
	SENSING_COLORISTOUCHINGCOLOR,
	SENSING_DISTANCETO,
	SENSING_ASKANDWAIT,
	SENSING_ANSWER,
	SENSING_KEYPRESSED,
	SENSING_MOUSEDOWN,
	SENSING_MOUSEX,
	SENSING_MOUSEY,
	SENSING_SETDRAGMODE,
	SENSING_LOUDNESS,
	SENSING_TIMER,
	SENSING_RESETTIMER,
	SENSING_OF,
	SENSING_CURRENT,
	SENSING_DAYSSINCE2000,
	SENSING_USERNAME,

	// Operators Opcodes
	OPERATOR_ADD,
	OPERATOR_SUBTRACT,
	OPERATOR_MULTIPLY,
	OPERATOR_DIVIDE,
	OPERATOR_RANDOM,
	OPERATOR_GT,
	OPERATOR_LT,
	OPERATOR_EQUALS,
	OPERATOR_AND,
	OPERATOR_OR,
	OPERATOR_NOT,
	OPERATOR_JOIN,
	OPERATOR_LETTER_OF,
	OPERATOR_LENGTH,
	OPERATOR_CONTAINS,
	OPERATOR_MOD,
	OPERATOR_ROUND,
	OPERATOR_MATHOP,

	// Data Opcodes

	//// Variables
	DATA_VARIABLE,
	DATA_SETVARIABLETO,
	DATA_CHANGEVARIABLEBY,
	DATA_SHOWVARIABLE,
	DATA_HIDEVARIABLE,

	//// Lists
	DATA_LISTCONTENTS,
	DATA_ADDTOLIST,
	DATA_DELETEOFLIST,
	DATA_DELETEALLOFLIST,
	DATA_INSERTATLIST,
	DATA_REPLACEITEMOFLIST,
	DATA_ITEMOFLIST,
	DATA_ITEMNUMOFLIST,
	DATA_LENGTHOFLIST,
	DATA_LISTCONTAINSITEM,
	DATA_SHOWLIST,
	DATA_HIDELIST,

	// Custom Block Opcodes
	PROCEDURES_DEFINITION,
	PROCEDURES_CALL,
	ARGUMENT_REPORTER_STRING_NUMBER,
	ARGUMENT_REPORTER_BOOLEAN
}

export function getOpcodeName(opcode: Opcode): string {
	return Opcode[opcode].toLowerCase();
}
